sudo: required
addons:
  chrome: stable
dist: trusty
language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- ng build --prod --aot
- ng test
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: Xp9ernVU2CZd1DtW+54+xeTThmw1mVJMrxW4fw7Abbk9tPkcajT8/sL2SJOBIFFLRK/1sPJtyZsHyMr1wLoNmt06WPVEs2gOLgE8a7q8jteICOUDnz3Scx8q0u77c8VFSQOhHQW2BEnHD4fR/QSAAUSVLBrMJnSoiFzdFijyueZXX+zJCwniPtycI9FkZOIGO4GTHQn5FFlHXqxEdREnBezXXbZIHI4AtnHQzzemWgoiQgFj+HAK/hW5XQgaPpW+/DK3q6NbpLHE5sF1hMEGx2PrBP47xfAo1qPODimtN/QMAQqJrhPmfTKdR0LSle3KeD1YXbT+exjwPNEYZVROuvE5gh1wbUIeIscSeQsxLQ6AbcsMBt9aOUhQBAh+zAse+FTigM/Qg98Y4L8w6t2Cs2E4zxnRLiO0Qh+Oaut7HJvjryrOshvIFIWAANdQdnKI0WvhRjUv+PUMBMsrxV6CiZMBSLiOWJrwYKM+jUY7tHXtCY4sDvia9sylWr0O9YqXrxMeNq7czW/emazxj+tsZnF998PlrnZSAK4d909Ho5xRXkMoW8MVg0TV2fpZz0r26TvZ+gVUwBQbLBi/5FfVdIg1XTWsFL3zdFzhSdgpohDzCZIR28PEl8ardRSCrd/u6DpI1bM3mvUAYnm3rEqcTnfTa0l9NFno9V+I5oAgPmA=
  organization: team-hydra
  space: julekalender
  on:
    repo: DanielIdris/Julekalender
