sudo: required
addons:
  chrome: stable
dist: trusty
language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- ng build --prod --aot
- ng test
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris@bouvet.no
  password:
    secure: WFCnPXVm6+PHKgbl7NdytDp2v2+QCI+Y94vVUq7dzjUdUSxiCluLSq8C3JE8Pwxe8g0E87MY6r/S7MeESR13V1IJXDGBeZ7i103pjwPL+IbcjZl6Kx4PVBoHEMHf+u3LO75bQuFjgcKvEVcd+LhZxFHlDROf9JRbOsdU7HBl3JdtzUBCuDss6SSAOHwrgKv2lnx2S6n+YJLWkuhfH4Ja4QzIGBxQXgTgRcNOt57lA0ts7R7h4h67OJ5sED6j9aaBsoAXToX7v9GuR7vDRCqDPOmmHVqS/vlXDLsGa81rZgefhZN/GrjwSDueqYb//LJNdGvyFP2MbDVk/SGMwmRFVW/4sL5bOuF0O+kYIP+yPfXk7Sa3/Ntd61SNJJGgWVsU+NuAMqxc5RUOIg5HF2z4aS/RkYGToVJwY4zRYSfxBKqvOwv/BBTf0X3lqm0YcMfvkn9zfn5o9Pad6eUO0faLFR8927k6AK7eXRYmX5Ez2cLu7p7dTvIYYnWxQqDnaCgLf+q+nsTpW1CPQ5yJGmonU2rjzxN71jNBISILrrlCQN7t4uXBlaxUrv0hHiHzvZE4XLf6Z0y47ET0wu23gQj6ElYO2iKY+Lm690tY/2TOxF5xf3jMCbHnrV1W6d+ucS5M7NktqHNA7yQ1HDueXnraWANtOzGGfMjnpuQkrIwXNdw=
  organization: team-hydra
  space: julekalender
  on:
    repo: DanielIdris/Julekalender
